import type { Account, Kategorie } from "../types/db";
import { tagsForKonto } from "../domain/est/tagsForKonto";

type Seed = Omit<Account, "id" | "created_at">;

function a(
  konto_nr: string,
  bezeichnung: string,
  kategorie: Kategorie,
  ust_satz: number | null = null
): Seed {
  const tags = tagsForKonto(konto_nr);
  return {
    konto_nr,
    bezeichnung,
    kategorie,
    ust_satz,
    skr: "SKR03",
    is_active: true,
    // Phase 3 / Schritt 6: ESt-Anlagen-Tag-Seed aus dem Range-Mapping.
    // Konten außerhalb der Mapping-Ranges (z. B. 0100-er, 1200, 1400)
    // bekommen ein leeres Array — Nutzer können später im AccountsPage
    // manuell zuordnen, ohne Null-Check in den Konsumenten.
    tags,
  };
}

// Comprehensive SKR03 chart of accounts.
// Reference: DATEV SKR03 Standard-Kontenrahmen (public specification).
// Grouped to match the Bilanz/GuV structure expected by the reports.
export const SKR03_SEED: Seed[] = [
  // === Klasse 0 — Anlagevermögen (Aktiva) ===
  a("0100", "Grundstücke ohne Bauten", "aktiva"),
  a("0200", "Grundstücke mit Bauten", "aktiva"),
  a("0300", "Technische Anlagen und Maschinen", "aktiva"),
  a("0320", "Büroeinrichtung", "aktiva"),
  a("0400", "Maschinen", "aktiva"),
  a("0410", "Werkzeuge", "aktiva"),
  a("0420", "Geschäftsausstattung", "aktiva"),
  a("0430", "Ladeneinrichtung", "aktiva"),
  a("0440", "Büromaschinen, EDV-Anlagen", "aktiva"),
  a("0480", "Geringwertige Wirtschaftsgüter", "aktiva"),
  a("0650", "LKW", "aktiva"),
  a("0670", "PKW", "aktiva"),
  a("0700", "Konzessionen und gewerbliche Schutzrechte", "aktiva"),
  a("0710", "Geschäfts- oder Firmenwert", "aktiva"),
  a("0720", "Sonstige Software", "aktiva"),
  a("0800", "Beteiligungen an verbundenen Unternehmen", "aktiva"),
  a("0860", "Gewinnvortrag vor Verwendung", "passiva"),
  a("0900", "Sonstige Ausleihungen", "aktiva"),

  // === Klasse 9 — Eröffnungsbilanz / Saldenvortrag (Passiva per Konvention) ===
  // Sprint 7.5: Konto 9000 wird in der Musterfirma-Demo als Gegenkonto
  // für die 8 Eröffnungsbilanz-Buchungen genutzt. SKR03 ordnet das
  // Eröffnungsbilanzkonto fachlich dem passiva-Bereich zu (Entscheidung 34 A).
  a("9000", "Eröffnungsbilanzkonto (Saldenvortrag)", "passiva"),

  // === Klasse 1 — Umlaufvermögen / Finanzkonten (Aktiva) ===
  a("1000", "Kasse", "aktiva"),
  a("1100", "Postbank", "aktiva"),
  a("1200", "Bank", "aktiva"),
  a("1210", "Bank PayPal", "aktiva"),
  a("1220", "Bank Sparkasse", "aktiva"),
  a("1230", "Bank DKB", "aktiva"),
  a("1240", "Bank Commerzbank", "aktiva"),
  a("1300", "Wechsel", "aktiva"),
  a("1400", "Forderungen aus Lieferungen und Leistungen", "aktiva"),
  a("1401", "Forderungen - Zweifelhaft", "aktiva"),
  a("1410", "Forderungen gegenüber verbundenen Unternehmen", "aktiva"),
  a("1500", "Sonstige Vermögensgegenstände", "aktiva"),
  a("1501", "Kautionen", "aktiva"),
  a("1510", "Durchlaufende Posten", "aktiva"),
  a("1540", "Steuererstattungsansprüche gegenüber Finanzbehörden", "aktiva"),
  a("1545", "Körperschaftsteuererstattungsansprüche", "aktiva"),
  a("1548", "Forderungen an Finanzamt", "aktiva"),
  a("1560", "Finanzamt Umsatzsteuer-Vorauszahlungen", "aktiva"),
  a("1571", "Abziehbare Vorsteuer 7 %", "aktiva", 7),
  a("1572", "Abziehbare Vorsteuer aus innergem. Erwerb", "aktiva", 19),
  a("1574", "Abziehbare Vorsteuer aus innergem. Erwerb (Kz 61)", "aktiva", 19),
  a("1575", "Abziehbare Vorsteuer aus Reverse-Charge", "aktiva", 19),
  a("1576", "Abziehbare Vorsteuer 19 %", "aktiva", 19),
  a("1577", "Abziehbare Vorsteuer nach §13b UStG", "aktiva", 19),
  a("1580", "Vorsteuer-Berichtigung nach §15a UStG", "aktiva"),
  a("1590", "Durchlaufende Posten Vorsteuer", "aktiva"),

  // === Klasse 2 — Eigenkapital / Rückstellungen / Privat (Passiva) ===
  a("2000", "Privatentnahmen allgemein", "passiva"),
  a("2030", "Privatentnahmen Sachwerte", "passiva"),
  a("2040", "Privatentnahmen Wohnung", "passiva"),
  a("2100", "Privateinlagen", "passiva"),
  a("2150", "Einkommensteuer-Vorauszahlungen", "passiva"),
  a("2190", "Sonderausgaben (beschränkt abziehbar)", "passiva"),
  a("2200", "Außergewöhnliche Belastungen", "passiva"),
  a("2300", "Grundkapital / Gezeichnetes Kapital", "passiva"),
  a("2400", "Gewinnrücklagen", "passiva"),
  a("2600", "Rückstellungen für Pensionen", "passiva"),
  a("2610", "Steuerrückstellungen", "passiva"),
  a("2620", "Sonstige Rückstellungen", "passiva"),
  a("2700", "Sonstige neutrale Erträge", "ertrag"),
  a("2800", "Sonstige neutrale Aufwendungen", "aufwand"),

  // === Klasse 1 (high numbers) — Verbindlichkeiten / USt (Passiva) ===
  a("1600", "Verbindlichkeiten aus Lieferungen und Leistungen", "passiva"),
  a("1610", "Verbindlichkeiten gegenüber verbundenen Unternehmen", "passiva"),
  a("1700", "Sonstige Verbindlichkeiten", "passiva"),
  a("1705", "Kreditkartenabrechnungen", "passiva"),
  a("1740", "Verbindlichkeiten Lohn/Gehalt", "passiva"),
  a("1741", "Verbindlichkeiten soziale Sicherheit", "passiva"),
  a("1742", "Verbindlichkeiten Lohnsteuer", "passiva"),
  a("1771", "Umsatzsteuer 7 %", "passiva", 7),
  a("1774", "Umsatzsteuer aus innergem. Erwerb 19 %", "passiva", 19),
  a("1775", "Umsatzsteuer nach §13b UStG 19 %", "passiva", 19),
  a("1776", "Umsatzsteuer 19 %", "passiva", 19),
  a("1780", "Umsatzsteuer-Vorauszahlungen", "passiva"),
  a("1781", "Umsatzsteuer laufendes Jahr", "passiva"),
  a("1789", "Umsatzsteuer Vorjahr", "passiva"),
  a("1790", "Umsatzsteuer nicht fällig", "passiva"),

  // === Klasse 3 — Wareneinkauf (Aufwand) ===
  a("3000", "Roh-, Hilfs- und Betriebsstoffe (Aufwand)", "aufwand", 19),
  a("3100", "Fremdleistungen", "aufwand", 19),
  a("3120", "Bauleistungen § 13b Abs. 2 Nr. 2 UStG", "aufwand", 19),
  a("3130", "Gebäudereinigung § 13b Abs. 2 Nr. 3 UStG", "aufwand", 19),
  a("3200", "Wareneingang", "aufwand", 19),
  a("3300", "Wareneingang 7 % Vorsteuer", "aufwand", 7),
  a("3400", "Wareneingang 19 % Vorsteuer", "aufwand", 19),
  a("3425", "Innergemeinschaftlicher Erwerb 19 % (Bemessungsgrundlage)", "aufwand", 19),
  a("3500", "Wareneingang steuerfrei", "aufwand", 0),
  a("3730", "Erhaltene Skonti 7 %", "aufwand", 7),
  a("3736", "Erhaltene Skonti 19 %", "aufwand", 19),
  a("3800", "Bezugsnebenkosten", "aufwand", 19),

  // === Klasse 4 — Betriebliche Aufwendungen (Aufwand) ===
  a("4100", "Löhne", "aufwand"),
  a("4110", "Gehälter", "aufwand"),
  a("4120", "Geschäftsführergehalt", "aufwand"),
  a("4125", "Freiwillige soziale Aufwendungen", "aufwand"),
  a("4130", "Gesetzliche soziale Aufwendungen", "aufwand"),
  a("4138", "Beiträge zur Knappschaftsversicherung", "aufwand"),
  a("4140", "Beiträge zur Berufsgenossenschaft", "aufwand"),
  a("4145", "Umlage U1 / U2", "aufwand"),
  a("4200", "Raumkosten", "aufwand"),
  a("4210", "Miete", "aufwand"),
  a("4220", "Pacht", "aufwand"),
  a("4230", "Heizung", "aufwand", 19),
  a("4240", "Gas, Strom, Wasser", "aufwand", 19),
  a("4250", "Reinigung", "aufwand", 19),
  a("4260", "Instandhaltung betrieblicher Räume", "aufwand", 19),
  a("4280", "Sonstige Raumkosten", "aufwand", 19),
  a("4360", "Versicherungen", "aufwand"),
  a("4370", "Sonstige Abgaben", "aufwand"),
  a("4380", "Beiträge", "aufwand"),
  a("4390", "Sonstige Raumkosten", "aufwand", 19),
  a("4500", "Fahrzeugkosten", "aufwand"),
  a("4510", "Kfz-Versicherungen", "aufwand"),
  a("4520", "Kfz-Steuer", "aufwand"),
  a("4530", "Laufende Kfz-Betriebskosten", "aufwand", 19),
  a("4540", "Kfz-Reparaturen", "aufwand", 19),
  a("4550", "Garagenmiete", "aufwand", 19),
  a("4560", "Leasingkosten Kfz", "aufwand", 19),
  a("4580", "Sonstige Kfz-Kosten", "aufwand", 19),
  a("4600", "Werbekosten", "aufwand", 19),
  a("4610", "Streuartikel", "aufwand", 19),
  a("4620", "Werbedrucksachen", "aufwand", 19),
  a("4630", "Geschenke an Kunden", "aufwand", 19),
  a("4635", "Geschenke nicht abzugsfähig (über 35 €)", "aufwand", 19),
  a("4650", "Bewirtungskosten", "aufwand", 19),
  a("4654", "Nicht abzugsfähige Bewirtungskosten (30 %)", "aufwand"),
  a("4660", "Reisekosten Arbeitnehmer", "aufwand", 19),
  a("4670", "Reisekosten Unternehmer", "aufwand", 19),
  a("4680", "Fortbildungskosten Arbeitnehmer", "aufwand", 19),
  a("4700", "Transportkosten", "aufwand", 19),
  a("4710", "Verpackungsmaterial", "aufwand", 19),
  a("4730", "Ausgangsfrachten", "aufwand", 19),
  a("4800", "Reparaturen", "aufwand", 19),
  a("4805", "Reparaturen an techn. Anlagen und Maschinen", "aufwand", 19),
  a("4806", "Reparaturen an Geschäftsausstattung", "aufwand", 19),
  a("4807", "Wartungskosten", "aufwand", 19),
  a("4809", "Sonstige Reparatur- und Instandhaltungskosten", "aufwand", 19),
  a("4810", "Mietleasing", "aufwand", 19),
  a("4820", "Abschreibungen Sachanlagen", "aufwand"),
  a("4830", "Abschreibungen Sachanlagen (ohne Gebäude)", "aufwand"),
  a("4840", "Abschreibungen Geringwertige Wirtschaftsgüter", "aufwand"),
  a("4855", "Abschreibungen auf Forderungen", "aufwand"),
  a("4900", "Sonstige betriebliche Aufwendungen", "aufwand", 19),
  a("4909", "Fremdleistungen Verwaltung", "aufwand", 19),
  a("4910", "Porto", "aufwand"),
  a("4920", "Telefon", "aufwand", 19),
  a("4925", "Internet", "aufwand", 19),
  a("4930", "Bürobedarf", "aufwand", 19),
  a("4940", "Zeitschriften, Bücher", "aufwand", 7),
  a("4945", "Fachliteratur", "aufwand", 7),
  a("4950", "Fortbildungskosten", "aufwand", 19),
  a("4955", "Rechts- und Beratungskosten", "aufwand", 19),
  a("4957", "Abschluss- und Prüfungskosten", "aufwand", 19),
  a("4958", "Buchführungskosten", "aufwand", 19),
  a("4960", "Mieten für Einrichtungen", "aufwand", 19),
  a("4970", "Nebenkosten des Geldverkehrs", "aufwand"),
  a("4980", "Sonstiger Betriebsbedarf", "aufwand", 19),
  a("4985", "Werkzeuge und Kleingeräte", "aufwand", 19),

  // === Klasse 8 — Erlöse (Ertrag) ===
  a("8100", "Steuerfreie Erlöse §4 Nr.1a UStG", "ertrag", 0),
  a("8120", "Steuerfreie innergemeinschaftliche Lieferungen", "ertrag", 0),
  a("8125", "Steuerfreie EG-Lieferungen", "ertrag", 0),
  a("8130", "Steuerfreie Umsätze §4 Nr. 8 ff UStG", "ertrag", 0),
  a("8150", "Sonstige steuerfreie Umsätze Inland", "ertrag", 0),
  a("8200", "Erlöse", "ertrag"),
  a("8300", "Erlöse 7 % USt", "ertrag", 7),
  a("8310", "Erlöse 7 % USt aus im anderen EG-Land steuerpflichtigen Lieferungen", "ertrag", 7),
  a("8315", "Erlöse aus innergem. Erwerb 7 %", "ertrag", 7),
  a("8336", "Erlöse aus im Inland steuerpflichtigen EU-Lieferungen 7 %", "ertrag", 7),
  a("8400", "Erlöse 19 % USt", "ertrag", 19),
  a("8410", "Erlöse 19 % USt aus Reverse-Charge", "ertrag", 19),
  a("8450", "Erlöse 19 %, die nicht der Gewerbesteuer unterliegen", "ertrag", 19),
  a("8500", "Sonstige Erlöse", "ertrag", 19),
  a("8501", "Sonstige Erlöse steuerfrei", "ertrag", 0),
  a("8505", "Sonstige Erlöse 7 %", "ertrag", 7),
  a("8510", "Provisionserlöse", "ertrag", 19),
  a("8590", "Mieterträge", "ertrag"),
  a("8591", "Mieterträge 19 %", "ertrag", 19),
  a("8700", "Erlösschmälerungen", "ertrag", 19),
  a("8730", "Gewährte Skonti 19 %", "ertrag", 19),
  a("8731", "Gewährte Skonti 7 %", "ertrag", 7),
  a("8780", "Sonstige Erlösschmälerungen", "ertrag", 19),
  a("8800", "Zinserträge", "ertrag"),
  a("8820", "Zinserträge aus Bankguthaben", "ertrag"),
  a("8900", "Sonstige Zinsen und ähnliche Erträge", "ertrag"),
  a("8920", "Dividendenerträge", "ertrag"),

  // === Klasse 7 — Sonstige Aufwendungen (Aufwand) ===
  a("7000", "Zinsaufwendungen", "aufwand"),
  a("7100", "Zinsaufwendungen für kurzfristige Verbindlichkeiten", "aufwand"),
  a("7300", "Sonstige betriebliche Aufwendungen", "aufwand", 19),
  a("7610", "Betriebssteuern", "aufwand"),
];
