-- ============================================================================
-- harouda-app · DEAKTIVIERT
-- (Charge 15, Phase 1 · Schuld 14-aleph)
--
-- Diese Migration ist FUNKTIONAL ERSETZT durch:
--   supabase/migrations/0050_drop_legacy_settings_and_recreate.sql
--
-- Grund der Deaktivierung:
--   0044 enthielt "create table if not exists public.settings" mit
--   single-row-JSONB-Struktur. In 'harouda' existiert public.settings
--   bereits seit 0001_init.sql (Zeile 78 ff.) als wide-table. Das
--   "if not exists" uebersprang die Erstellung; nachfolgende Constraints
--   schlugen fehl mit:
--     ERROR 42703: column "mandant_id" of relation "public.settings"
--                  does not exist
--
-- Loesung:
--   Migration 0050 verwirft die wide-table (drop table cascade) und
--   legt public.settings in der erwarteten JSONB-Struktur neu an.
--   Der DDL-Inhalt (Tabelle, Index, Trigger, RLS-Policies) wurde
--   unveraendert aus diesem File nach 0050 uebernommen.
--
-- Datei beibehalten:
--   Aus historischen Gruenden (Migration-History, Code-Review-
--   Nachvollziehbarkeit) wird diese Datei NICHT geloescht. Sie ist
--   als No-op-Marker zu verstehen.
--
-- Auswirkung auf db push:
--   Diese Datei enthaelt nur Kommentare. db push fuehrt sie aus,
--   ohne Effekt. Reihenfolge zwischen 0044 und 0050 spielt keine
--   Rolle, da 0050 den finalen Zustand idempotent herstellt.
-- ============================================================================

-- (Inhalt absichtlich leer. Siehe 0050.)
